### ISSUE TITLE
Store colors used in the app in a constant files

### ISSUE THREAD

**Issue by Grimmys** [Grimmys/PokeTCGBot#11]
discord.py is relying on hexadecimal notation for the color of elements in the UI.

It's somewhat annoying to have to look everytime for the hexadecimal code of the color we want to select, or decrypt the color that is already put in some place.

Therefore, it would be nice to have a constant file holding the values for every color commonly used in the project.

The format to follow for the values is the following: `0xffffff` (0x and then 6 digits).

**Comment by skanderboudawara** [comment]
Done :D

**Comment by Grimmys** [comment]
Implemented by #17
