### ISSUE TITLE
Extract script to fetch all cards from the API to the main application

### ISSUE THREAD

**Issue by Grimmys** [Grimmys/PokeTCGBot#13]
The independently run script to fetch all cards should be put in the regular workflow run of the application, in order to simplify the startup of the bot in a fresh environment.

Since this fetching is an **heavy** operation, it should be done only if the `cards.p` file (the file where the fetched cards are stored) is not already present.

Then, when someone want to update their data set of cards (like when a **new** set is released), they just have to delete the cached file and the API call would be done once again at next startup.

**Comment by muddi900** [comment]
So the server should check if the pickle file exists in the local directory and then run the pull all cards from the api?

**Comment by Grimmys** [comment]
@muddi900 yes, it should run the API call only if the pickle file is not present. Does it make sense for you?

I guess an alternative solution could be to still have this process run independently (as a script), but add the generated `card.p` to the versioning.

In my opinion, the important thing in this issue is to fix the workflow run requiring currently to run the script before launching the app when we are starting from a fresh setup.

**Comment by muddi900** [comment]
If it is being run in a Docker container, it will rebuild every time it's deployed. Wouldn't a better solution be to check for an Env var like `PICKLE_LOCATION_URI` and check if the item exist in the path and then run it?

**Comment by Grimmys** [comment]
If we are going to have a Docker-based development (it's not actually the case, but it will probably in the future when we will scale to a better server and real database support), then it would be best to have the file in the versioning I guess, so the Docker container will always take the content from this file instead of rebuild it.

The solution you are talking about (i.e. check for an env variable containing the path) would not be working, because unless we want to attach a persistent hard drive to our Docker container, the application would recreate the data from scratch at every run since everything would be rebuilt.
And in this case, each restart of the bot would be really long.

Please, correct me if I didn't understand correctly what you meant.

**Comment by Grimmys** [comment]
Done through https://github.com/Grimmys/PokeTCGBot/commit/af16bd6a1904e412dabc97d9fe6bf8d038d3e604, cards loaded from API and stored in pickle format are now part of the versioning.
